"""empty message

Revision ID: 28d1f4d6bee2
Revises: d4ef3547a228
Create Date: 2021-08-16 16:02:19.781716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d1f4d6bee2'
down_revision = 'd4ef3547a228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('humidity', sa.String(length=120), nullable=False),
    sa.Column('irrigation', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('humidity'),
    sa.UniqueConstraint('irrigation')
    )
    op.create_table('planttype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fantansy_name', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('family_name', sa.String(length=120), nullable=False),
    sa.Column('idPlanttype', sa.Integer(), nullable=False),
    sa.Column('avatar', sa.String(length=120), nullable=False),
    sa.Column('idIndicator', sa.Integer(), nullable=False),
    sa.Column('user_photos', sa.String(length=120), nullable=False),
    sa.Column('water', sa.String(length=120), nullable=False),
    sa.Column('temperature_range', sa.String(length=120), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idIndicator'], ['indicator.id'], ),
    sa.ForeignKeyConstraint(['idPlanttype'], ['planttype.id'], ),
    sa.ForeignKeyConstraint(['idUser'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avatar'),
    sa.UniqueConstraint('family_name'),
    sa.UniqueConstraint('fantansy_name'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('temperature_range'),
    sa.UniqueConstraint('user_photos'),
    sa.UniqueConstraint('water')
    )
    op.add_column('user', sa.Column('avatar', sa.String(length=250), nullable=False))
    op.add_column('user', sa.Column('credential', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('nickname', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('rol', sa.Boolean(), nullable=False))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'rol')
    op.drop_column('user', 'nickname')
    op.drop_column('user', 'credential')
    op.drop_column('user', 'avatar')
    op.drop_table('plant')
    op.drop_table('planttype')
    op.drop_table('indicator')
    # ### end Alembic commands ###
