"""empty message

Revision ID: defdf48f2f47
Revises: 28d1f4d6bee2
Create Date: 2021-08-16 23:10:50.178353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'defdf48f2f47'
down_revision = '28d1f4d6bee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('fantasy_name', sa.String(length=120), nullable=False))
    op.drop_constraint('plant_fantansy_name_key', 'plant', type_='unique')
    op.create_unique_constraint(None, 'plant', ['fantasy_name'])
    op.drop_column('plant', 'fantansy_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('fantansy_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'plant', type_='unique')
    op.create_unique_constraint('plant_fantansy_name_key', 'plant', ['fantansy_name'])
    op.drop_column('plant', 'fantasy_name')
    # ### end Alembic commands ###
